package Player;

import Board.Square;
import Ship.Ship;

import java.util.ArrayList;
import java.util.List;

public class AiPlayer extends Player {
    List<Ship> ships = new ArrayList<>();
    List<Square> shots = new ArrayList<>();


    public int[] getShotCoors() {
        //return coords generated by AI
        int[] coords = {0,0};
        return coords;
    }

    @Override
    public String getName() {
        return "dupa";
    }

}
